"""create_users_table
Revision ID: ffdc0a98111c
Revises:
Create Date: 2020-11-20 15:06:02.230689
"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'ffdc0a98111c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(
                        length=40), nullable=False),
                    sa.Column('firstname', sa.String(
                        length=50), nullable=False),
                    sa.Column('lastname', sa.String(
                        length=50), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('profile_pic', sa.String(
                        length=255), nullable=True),
                    sa.Column('bio', sa.Text(), nullable=False),
                    sa.Column('join_date', sa.Date(), nullable=False),
                    sa.Column('hashed_password', sa.String(
                        length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")

    op.create_table('artworks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=50), nullable=False),
                    sa.Column('artist_name', sa.String(
                        length=50), nullable=False),
                    sa.Column('year', sa.Integer(), nullable=False),
                    sa.Column('height', sa.String(length=50), nullable=False),
                    sa.Column('width', sa.String(length=50), nullable=False),
                    sa.Column('available', sa.Boolean(), nullable=True),
                    sa.Column('materials', sa.Enum('OIL', 'ACRYLIC', 'MULTIMEDIA', 'BALLPOINT', 'CHARCOAL', 'WATERCOLOR', 'PENCIL', 'COLORPENCIL',
                                                   'PRINT', 'PASTEL', 'TEMPERA', 'SILKSCREEN', 'FRESCO', 'MARBLE', 'WOODBLOCK', name='artworktypesenum'), nullable=False),
                    sa.Column('image', sa.String(length=255), nullable=True),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('owner_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE artworks SET SCHEMA {SCHEMA};")

    op.create_table('reviews',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('review', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('reviewer_id', sa.Integer(), nullable=False),
                    sa.Column('receiver_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE reviews SET SCHEMA {SCHEMA};")


    op.create_table('shopping_carts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('_items', sa.String(length=500), nullable=False),
                    sa.Column('owner_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE shopping_carts SET SCHEMA {SCHEMA};")


    op.create_table('art_listings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('price', sa.String(length=50), nullable=False),
                    sa.Column('list_date', sa.Date(), nullable=False),
                    sa.Column('amount_available',
                              sa.Integer(), nullable=False),
                    sa.Column('artwork_id', sa.Integer(), nullable=False),
                    sa.Column('owner_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE art_listings SET SCHEMA {SCHEMA};")


    op.create_table('auction_listings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('start_bid', sa.String(
                        length=50), nullable=False),
                    sa.Column('list_date', sa.DateTime(), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('current_bid', sa.String(
                        length=50), nullable=False),
                    sa.Column('last_update', sa.DateTime(), nullable=False),
                    sa.Column('auction_deadline',
                              sa.DateTime(), nullable=False),
                    sa.Column('artwork_id', sa.Integer(), nullable=False),
                    sa.Column('owner_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE auction_listings SET SCHEMA {SCHEMA};")


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auction_listings')
    op.drop_table('art_listings')
    op.drop_table('shopping_carts')
    op.drop_table('reviews')
    op.drop_table('artworks')
    op.drop_table('users')
    # ### end Alembic commands ###
